package com.quleme.ui.text.boy

import com.quleme.ui.text.HomeTakeoffAnimationStyle

object BoyText {
    // Common
    const val CANCEL = "取消"
    const val SAVE = "保存"
    const val CONFIRM = "确定"
    const val DELETE = "删除"
    const val EDIT = "编辑"

    // Navigation
    const val NAV_HOME = "主页"
    const val NAV_STATISTICS = "统计"
    const val NAV_SETTINGS = "设置"

    // Auth / Lock
    const val AUTH_TITLE = "身份验证"
    const val AUTH_SUBTITLE = "使用系统锁屏密码或生物识别验证身份"
    const val AUTH_NEGATIVE = "取消"
    const val LOCK_HINT_USE_SYSTEM_AUTH = "请使用系统锁屏或生物识别解锁"
    const val LOCK_HINT_UNSUPPORTED = "当前页面不支持系统认证"
    const val LOCK_HINT_ENABLE_SYSTEM_AUTH = "请先在系统设置中启用锁屏密码或生物识别"
    const val LOCK_HINT_FAILED = "验证失败，请重试"
    const val LOCK_WELCOME_BACK = "欢迎回来"
    const val LOCK_RETRY = "重新验证"
    const val LOCK_GO_TO_SYSTEM_SETTINGS = "前往系统设置"

    // Home
    val HOME_TAKEOFF_ANIMATION_STYLE = HomeTakeoffAnimationStyle.PLANE_TAKEOFF
    const val HOME_ERROR_PREFIX = "哎呀，出错了: "
    const val HOME_WEEK_OVERVIEW = "本周概览"
    const val HOME_STATS_COUNT = "次数"
    const val HOME_STATS_STATUS = "状态"
    const val HOME_STATUS_SAGE_MODE = "贤者模式"
    const val HOME_STATUS_ACTIVE = "活跃"
    const val HOME_TAKEOFF = "起飞"
    const val HOME_TAKEOFF_AGAIN = "再来一发"
    const val HOME_GREETING_DAWN = "凌晨好！机长"
    const val HOME_GREETING_MORNING = "早上好！机长"
    const val HOME_GREETING_NOON = "中午好！机长"
    const val HOME_GREETING_AFTERNOON = "下午好！机长"
    const val HOME_GREETING_EVENING = "晚上好！机长"
    const val HOME_TODAY_NOT_YET = "今日还没起飞"
    const val HOME_KEEP_MOOD = "保持好心情~"
    const val HOME_DONT_FORGET_LOVE = "别忘了爱自己哦"
    const val HOME_HEALTH_TIP_TITLE = "💡 健康小贴士"
    const val HOME_HEALTH_MSG_TODAY_MANY = "今天起飞有点多次啦，注意身体哦机长 ✈️"
    const val HOME_HEALTH_MSG_TODAY_ONCE = "今天已经起飞啦，心情不错吧~ ✨"
    const val HOME_HEALTH_MSG_FREQUENT = "最近有点频繁呢，注意劳逸结合哦 💙"
    const val HOME_HEALTH_MSG_HEALTHY = "节奏很健康！继续保持~ ✨"
    const val HOME_UNKNOWN_ERROR = "未知错误"
    const val HOME_DATE_PATTERN = "M月d日 EEEE"

    fun homeTodayRecorded(count: Int): String = "今日已起飞 $count 次 ✨"

    // Statistics
    const val STAT_TAB_WEEK = "本周"
    const val STAT_TAB_MONTH = "本月"
    const val STAT_TAB_ALL = "全部"
    const val STAT_ADD_RECORD = "添加记录"
    const val STAT_EDIT_RECORD = "编辑记录"
    const val STAT_DELETE_CONFIRM_TITLE = "删除这条记录吗？"
    const val STAT_DELETE_CONFIRM_TEXT = "删除后无法撤销。"
    const val STAT_WEEK_RECORD = "本周记录"
    const val STAT_CD_PREV_MONTH = "上个月"
    const val STAT_CD_NEXT_MONTH = "下个月"
    const val STAT_BACK_TO_CURRENT_MONTH = "回到本月"
    const val STAT_NO_RECORD = "暂无记录"
    const val STAT_ADD_ONE_RECORD = "添加一条记录"
    const val STAT_LABEL_DATE = "日期"
    const val STAT_LABEL_TIME = "时间"
    const val STAT_LABEL_NOTE_OPTIONAL = "备注，可选"
    const val STAT_ERROR_DATE_TIME_INVALID = "日期或时间格式不正确"
    const val STAT_TOTAL = "累计记录"
    const val STAT_MAX_STREAK = "最长连续"
    const val STAT_AVG_FREQUENCY = "平均频率"
    const val STAT_UNIT_TIMES = "次"
    const val STAT_UNIT_DAYS = "天"
    const val STAT_UNIT_TIMES_PER_WEEK = "次/周"
    const val STAT_ADVICE_LOW = "频率控制得很好，继续保持！👍"
    const val STAT_ADVICE_MEDIUM = "频率适中，生活很健康哦~ ✨"
    const val STAT_ADVICE_HIGH = "最近有点频繁，要注意身体休息哦 🛌"
    const val STAT_ADVICE_DEFAULT = "开始记录你的生活吧！"
    const val STAT_ADVICE_TITLE = "💡 近期建议"
    val STAT_WEEKDAY_HEADERS = listOf("一", "二", "三", "四", "五", "六", "日")

    fun statMonthTitle(year: Int, month: Int): String = "${year}年${month}月"
    fun statMonthTotal(total: Int): String = "共 $total 次"
    fun statDayTitle(month: Int, day: Int): String = "${month}月${day}日"
    fun statDayCount(count: Int): String = "记录 $count 次"

    // Settings
    const val SETTINGS_ENABLE_SYSTEM_AUTH_FIRST = "请先在系统设置中启用锁屏密码或生物识别"
    const val SETTINGS_EXPORT_SUCCESS = "数据导出成功 ✨"
    const val SETTINGS_EXPORT_FAILED = "导出失败了 😣"
    const val SETTINGS_RESTORE_SUCCESS = "数据恢复成功 ✨"
    const val SETTINGS_RESTORE_INVALID = "数据格式不对哦 😣"
    const val SETTINGS_RESTORE_FAILED = "恢复失败了 😣"
    const val SETTINGS_CLEAR_ALL_TITLE = "要清空所有数据吗？"
    const val SETTINGS_CLEAR_ALL_TEXT = "这个操作不能撤销哦，所有记录都会消失。"
    const val SETTINGS_CLEARED = "数据已清空"
    const val SETTINGS_CLEAR_CONFIRM = "确认清空"
    const val SETTINGS_THINK_AGAIN = "再想想"

    const val SETTINGS_WEBDAV_CONFIG_TITLE = "WebDAV 配置"
    const val SETTINGS_WEBDAV_SERVER_URL = "服务器地址"
    const val SETTINGS_WEBDAV_USERNAME = "用户名"
    const val SETTINGS_WEBDAV_PASSWORD = "密码"
    const val SETTINGS_WEBDAV_NEW_PASSWORD = "新密码（留空不改）"
    const val SETTINGS_WEBDAV_HINT = "备份文件会按当前导出格式上传，请妥善保管 WebDAV 账号。"
    const val SETTINGS_WEBDAV_DIRECTORY_OPTIONAL = "远程目录（可选）"
    const val SETTINGS_WEBDAV_CONFIG_SAVED = "WebDAV 配置已保存"
    const val SETTINGS_WEBDAV_CONFIG_SAVE_FAILED = "WebDAV 配置保存失败"

    const val SETTINGS_WEBDAV_RESTORE_TITLE = "从 WebDAV 恢复？"
    const val SETTINGS_WEBDAV_RESTORE_TEXT = "恢复会用云端最新备份替换本地记录，请确认已经选对备份来源。"
    const val SETTINGS_WEBDAV_RESTORE_CONFIRM = "确认恢复"
    const val SETTINGS_WEBDAV_RESTORE_SUCCESS = "WebDAV 恢复成功 ✨"
    const val SETTINGS_WEBDAV_RESTORE_FAILED = "WebDAV 恢复失败"

    const val SETTINGS_TITLE = "设置"
    const val SETTINGS_GROUP_PROFILE = "个人信息"
    const val SETTINGS_BIRTHDAY_PICK = "点击选择出生日期"
    const val SETTINGS_CURRENT_AGE = "当前年龄"
    const val SETTINGS_GROUP_SECURITY = "安全与隐私"
    const val SETTINGS_APP_LOCK = "应用锁"
    const val SETTINGS_APP_LOCK_SUBTITLE = "使用系统锁屏密码或生物识别"
    const val SETTINGS_GROUP_DATA = "数据管理"
    const val SETTINGS_BACKUP_DATA = "备份数据"
    const val SETTINGS_BACKUP_DATA_SUBTITLE = "用于数据迁移等场景"
    const val SETTINGS_RESTORE_DATA = "恢复数据"
    const val SETTINGS_RESTORE_DATA_SUBTITLE = "从 JSON 文件导入"
    const val SETTINGS_CLEAR_ALL = "清空所有数据"
    const val SETTINGS_CLEAR_ALL_SUBTITLE = "慎重操作"
    const val SETTINGS_GROUP_WEBDAV = "WebDAV 云备份"
    const val SETTINGS_WEBDAV_CONFIG = "WebDAV 配置"
    const val SETTINGS_WEBDAV_NOT_CONFIGURED = "未配置"
    const val SETTINGS_WEBDAV_TEST = "测试连接"
    const val SETTINGS_WEBDAV_TEST_SUBTITLE = "验证服务器地址和账号密码"
    const val SETTINGS_WEBDAV_TEST_OK = "WebDAV 连接正常"
    const val SETTINGS_WEBDAV_TEST_FAILED = "WebDAV 连接失败"
    const val SETTINGS_WEBDAV_BACKUP = "备份到 WebDAV"
    const val SETTINGS_WEBDAV_BACKUP_SUBTITLE = "上传为 quleme-backup-latest.json"
    const val SETTINGS_WEBDAV_BACKUP_OK = "WebDAV 备份成功 ✨"
    const val SETTINGS_WEBDAV_BACKUP_FAILED = "WebDAV 备份失败"
    const val SETTINGS_WEBDAV_RESTORE = "从 WebDAV 恢复"
    const val SETTINGS_WEBDAV_RESTORE_SUBTITLE = "下载云端最新备份并替换本地记录"

    fun settingsBirthDateText(date: String): String = "出生日期: $date"
    fun settingsAgeText(age: Int): String = "$age 岁"

    // Data layer errors
    const val WEBDAV_AUTH_FAILED = "WebDAV 认证失败"
    const val WEBDAV_NOT_FOUND = "未找到云端备份"

    fun webDavConnectionFailed(code: Int): String = "WebDAV 连接失败: $code"
    fun webDavUploadFailed(code: Int): String = "WebDAV 上传失败: $code"
    fun webDavDownloadFailed(code: Int): String = "WebDAV 下载失败: $code"
}
