package com.quleme.ui.text.boy

import com.quleme.ui.text.HomeTakeoffAnimationStyle

object BoyText {
    // Common
    const val CANCEL = "取消"
    const val SAVE = "保存日志"
    const val CONFIRM = "收到"
    const val DELETE = "销毁"
    const val EDIT = "修改"

    // Navigation
    const val NAV_HOME = "驾驶舱"
    const val NAV_STATISTICS = "飞行黑匣子"
    const val NAV_SETTINGS = "塔台设置"

    // Auth / Lock
    const val AUTH_TITLE = "机长身份核验"
    const val AUTH_SUBTITLE = "请验证指纹或面容以解锁操纵杆"
    const val AUTH_NEGATIVE = "放弃登机"
    const val LOCK_HINT_USE_SYSTEM_AUTH = "呼叫机长，请进行系统身份验证"
    const val LOCK_HINT_UNSUPPORTED = "当前设备机型不支持生物识别"
    const val LOCK_HINT_ENABLE_SYSTEM_AUTH = "请先在系统设置中启用指纹或密码锁"
    const val LOCK_HINT_FAILED = "核验失败，你是劫机的吗？重试一次"
    const val LOCK_WELCOME_BACK = "欢迎回到驾驶舱，机长"
    const val LOCK_RETRY = "再次验证"
    const val LOCK_GO_TO_SYSTEM_SETTINGS = "前往系统设置"

    // Home
    val HOME_TAKEOFF_ANIMATION_STYLE = HomeTakeoffAnimationStyle.PLANE_TAKEOFF
    const val HOME_ERROR_PREFIX = "塔台警告，出现故障: "
    const val HOME_WEEK_OVERVIEW = "本周航线概览"
    const val HOME_STATS_COUNT = "起飞架次"
    const val HOME_STATS_STATUS = "机体状态"
    const val HOME_STATUS_SAGE_MODE = "索然无味"
    const val HOME_STATUS_ACTIVE = "满油待命 ⛽"
    const val HOME_TAKEOFF = "请求起飞 🛫" 
    const val HOME_TAKEOFF_AGAIN = "复飞请求 ✌️"
    const val HOME_GREETING_DAWN = "还在熬夜修仙？夜航辛苦了，机长！"
    const val HOME_GREETING_MORNING = "早上好，机长！今天的风速很适合起飞"
    const val HOME_GREETING_NOON = "中午好！吃点好的补充一下燃油吧"
    const val HOME_GREETING_AFTERNOON = "下午好，机长！打起精神来"
    const val HOME_GREETING_EVENING = "晚上好！夜间航线已为你清空"
    const val HOME_TODAY_NOT_YET = "今日战机仍在机库休整"
    const val HOME_KEEP_MOOD = "保持愉快的心情~"
    const val HOME_DONT_FORGET_LOVE = "适度娱乐，注意身体哦"
    const val HOME_HEALTH_TIP_TITLE = "💡 塔台小贴士"
    const val HOME_HEALTH_MSG_TODAY_MANY = "机长！操纵杆都要被你撸冒烟了！塔台强制请求返航保养！🚨"
    const val HOME_HEALTH_MSG_TODAY_ONCE = "今日航班已平稳落地，身心通泰，感觉极佳~ ☁️"
    const val HOME_HEALTH_MSG_FREQUENT = "最近航线排得太满啦，塔台建议多喝点营养快线 🧃"
    const val HOME_HEALTH_MSG_HEALTHY = "飞行日志非常健康！王牌飞行员申请出战！😎"
    const val HOME_UNKNOWN_ERROR = "未知错误（可能是鸟击）"
    const val HOME_DATE_PATTERN = "M月d日 EEEE"

    fun homeTodayRecorded(count: Int): String = "今日已成功起飞 $count 架次 ✨"

    // Statistics
    const val STAT_TAB_WEEK = "本周航班"
    const val STAT_TAB_MONTH = "本月航线"
    const val STAT_TAB_ALL = "生涯总计"
    const val STAT_ADD_RECORD = "补录航班"
    const val STAT_EDIT_RECORD = "修改黑匣子"
    const val STAT_DELETE_CONFIRM_TITLE = "抹除这条飞行记录？"
    const val STAT_DELETE_CONFIRM_TEXT = "删除后雷达也找不回来了。"
    const val STAT_WEEK_RECORD = "本周航行轨迹"
    const val STAT_CD_PREV_MONTH = "上个月"
    const val STAT_CD_NEXT_MONTH = "下个月"
    const val STAT_BACK_TO_CURRENT_MONTH = "回到本月"
    const val STAT_NO_RECORD = "机库积灰了，暂无记录"
    const val STAT_ADD_ONE_RECORD = "添加一条起飞记录"
    const val STAT_LABEL_DATE = "起飞日期"
    const val STAT_LABEL_TIME = "离地时间"
    const val STAT_LABEL_NOTE_OPTIONAL = "航班备注，可选"
    const val STAT_ERROR_DATE_TIME_INVALID = "时间校准失败，请检查格式"
    const val STAT_TOTAL = "累计起飞架次"
    const val STAT_MAX_STREAK = "最长连飞"
    const val STAT_AVG_FREQUENCY = "平均出勤率"
    const val STAT_UNIT_TIMES = "架次"
    const val STAT_UNIT_DAYS = "天"
    const val STAT_UNIT_TIMES_PER_WEEK = "次/周"
    const val STAT_ADVICE_LOW = "飞机都快生锈了，机长真能忍！不过保持得很好 👍"
    const val STAT_ADVICE_MEDIUM = "定期巡航，引擎状态良好，健康生活典范~ ✈️"
    const val STAT_ADVICE_HIGH = "营养跟不上了哥！塔台强制要求休假，注意身体啊 🛌"
    const val STAT_ADVICE_DEFAULT = "启动引擎，开始记录你的第一本飞行日志！"
    const val STAT_ADVICE_TITLE = "💡 塔台评估报告"
    val STAT_WEEKDAY_HEADERS = listOf("一", "二", "三", "四", "五", "六", "日")

    fun statMonthTitle(year: Int, month: Int): String = "${year}年${month}月"
    fun statMonthTotal(total: Int): String = "共起飞 $total 架次"
    fun statDayTitle(month: Int, day: Int): String = "${month}月${day}日"
    fun statDayCount(count: Int): String = "起飞 $count 次"

    // Settings
    const val SETTINGS_ENABLE_SYSTEM_AUTH_FIRST = "请先在系统设置中启用锁屏密码或生物识别"
    const val SETTINGS_EXPORT_SUCCESS = "黑匣子数据导出成功 ✨"
    const val SETTINGS_EXPORT_FAILED = "导出失败，坠机了 😣"
    const val SETTINGS_RESTORE_SUCCESS = "数据恢复成功 ✨"
    const val SETTINGS_RESTORE_INVALID = "黑匣子破损，数据格式不对哦 😣"
    const val SETTINGS_RESTORE_FAILED = "恢复失败了 😣"
    const val SETTINGS_CLEAR_ALL_TITLE = "要炸毁整个机库吗？"
    const val SETTINGS_CLEAR_ALL_TEXT = "不可逆操作哦，你所有的飞行徽章和记录都会消失。"
    const val SETTINGS_CLEARED = "机库已清空"
    const val SETTINGS_CLEAR_CONFIRM = "确认炸毁"
    const val SETTINGS_THINK_AGAIN = "再想想"

    const val SETTINGS_WEBDAV_CONFIG_TITLE = "WebDAV 配置"
    const val SETTINGS_WEBDAV_SERVER_URL = "服务器地址"
    const val SETTINGS_WEBDAV_USERNAME = "用户名"
    const val SETTINGS_WEBDAV_PASSWORD = "密码"
    const val SETTINGS_WEBDAV_NEW_PASSWORD = "新密码（留空不改）"
    const val SETTINGS_WEBDAV_HINT = "备份文件会按当前导出格式上传，请妥善保管 WebDAV 账号。"
    const val SETTINGS_WEBDAV_DIRECTORY_OPTIONAL = "远程目录（可选）"
    const val SETTINGS_WEBDAV_CONFIG_SAVED = "WebDAV 配置已保存"
    const val SETTINGS_WEBDAV_CONFIG_SAVE_FAILED = "WebDAV 配置保存失败"

    const val SETTINGS_WEBDAV_RESTORE_TITLE = "从 WebDAV 恢复？"
    const val SETTINGS_WEBDAV_RESTORE_TEXT = "恢复会用云端最新备份替换本地记录，请确认已经选对备份来源。"
    const val SETTINGS_WEBDAV_RESTORE_CONFIRM = "确认恢复"
    const val SETTINGS_WEBDAV_RESTORE_SUCCESS = "WebDAV 恢复成功 ✨"
    const val SETTINGS_WEBDAV_RESTORE_FAILED = "WebDAV 恢复失败"

    const val SETTINGS_TITLE = "设置"
    const val SETTINGS_GROUP_PROFILE = "个人信息"
    const val SETTINGS_BIRTHDAY_PICK = "点击选择出生日期"
    const val SETTINGS_CURRENT_AGE = "当前年龄"
    const val SETTINGS_GROUP_SECURITY = "安全与隐私"
    const val SETTINGS_APP_LOCK = "应用锁"
    const val SETTINGS_APP_LOCK_SUBTITLE = "使用系统锁屏密码或生物识别"
    const val SETTINGS_GROUP_DATA = "数据管理"
    const val SETTINGS_BACKUP_DATA = "备份数据"
    const val SETTINGS_BACKUP_DATA_SUBTITLE = "用于数据迁移等场景"
    const val SETTINGS_RESTORE_DATA = "恢复数据"
    const val SETTINGS_RESTORE_DATA_SUBTITLE = "从 JSON 文件导入"
    const val SETTINGS_CLEAR_ALL = "清空所有数据"
    const val SETTINGS_CLEAR_ALL_SUBTITLE = "慎重操作"
    const val SETTINGS_GROUP_WEBDAV = "WebDAV 云备份"
    const val SETTINGS_WEBDAV_CONFIG = "WebDAV 配置"
    const val SETTINGS_WEBDAV_NOT_CONFIGURED = "未配置"
    const val SETTINGS_WEBDAV_TEST = "测试连接"
    const val SETTINGS_WEBDAV_TEST_SUBTITLE = "验证服务器地址和账号密码"
    const val SETTINGS_WEBDAV_TEST_OK = "WebDAV 连接正常"
    const val SETTINGS_WEBDAV_TEST_FAILED = "WebDAV 连接失败"
    const val SETTINGS_WEBDAV_BACKUP = "备份到 WebDAV"
    const val SETTINGS_WEBDAV_BACKUP_SUBTITLE = "上传为 quleme-backup-latest.json"
    const val SETTINGS_WEBDAV_BACKUP_OK = "WebDAV 备份成功 ✨"
    const val SETTINGS_WEBDAV_BACKUP_FAILED = "WebDAV 备份失败"
    const val SETTINGS_WEBDAV_RESTORE = "从 WebDAV 恢复"
    const val SETTINGS_WEBDAV_RESTORE_SUBTITLE = "下载云端最新备份并替换本地记录"

    fun settingsBirthDateText(date: String): String = "出生日期: $date"
    fun settingsAgeText(age: Int): String = "$age 岁"

    // Data layer errors
    const val WEBDAV_AUTH_FAILED = "WebDAV 认证失败"
    const val WEBDAV_NOT_FOUND = "未找到云端备份"

    fun webDavConnectionFailed(code: Int): String = "WebDAV 连接失败: $code"
    fun webDavUploadFailed(code: Int): String = "WebDAV 上传失败: $code"
    fun webDavDownloadFailed(code: Int): String = "WebDAV 下载失败: $code"
}
