package com.quleme.ui.text.girl

import com.quleme.ui.text.HomeTakeoffAnimationStyle

object GirlText {
    // Common
    const val CANCEL = "溜了溜了"
    const val SAVE = "保存Track"
    const val CONFIRM = "安排"
    const val DELETE = "删库跑路"
    const val EDIT = "重新打磨"

    // Navigation
    const val NAV_HOME = "打碟台"
    const val NAV_STATISTICS = "巡演记录"
    const val NAV_SETTINGS = "后台设置"

    // Auth / Lock
    const val AUTH_TITLE = "VIP后台验证"
    const val AUTH_SUBTITLE = "刷脸或指纹进入专属打碟区"
    const val AUTH_NEGATIVE = "撤退"
    const val LOCK_HINT_USE_SYSTEM_AUTH = "请出示系统VIP门票（锁屏/生物识别）"
    const val LOCK_HINT_UNSUPPORTED = "当前设备不支持高级安检"
    const val LOCK_HINT_ENABLE_SYSTEM_AUTH = "请先在系统设置录入您的VIP指纹/面容哦"
    const val LOCK_HINT_FAILED = "门票核验失败，再试一次？"
    const val LOCK_WELCOME_BACK = "DJ，您的主场到了"
    const val LOCK_RETRY = "重新刷票"
    const val LOCK_GO_TO_SYSTEM_SETTINGS = "去弄张门票"

    // Home
    val HOME_TAKEOFF_ANIMATION_STYLE = HomeTakeoffAnimationStyle.SAKURA_FADE
    const val HOME_ERROR_PREFIX = "哎呀，设备漏电了: "
    const val HOME_WEEK_OVERVIEW = "本周音乐节排期"
    const val HOME_STATS_COUNT = "搓碟次数"
    const val HOME_STATS_STATUS = "设备状态"
    const val HOME_STATUS_SAGE_MODE = "耳机断联 🎧" // 隐喻贤者模式
    const val HOME_STATUS_ACTIVE = "电量拉满 ⚡"
    const val HOME_TAKEOFF = "Drop the beat! 💽" // 准备开始
    const val HOME_TAKEOFF_AGAIN = "Encore! (返场) ✨"
    const val HOME_GREETING_DAWN = "修仙打碟？凌晨好，首席DJ！"
    const val HOME_GREETING_MORNING = "早安，百大DJ！今天也是元气满满的一天"
    const val HOME_GREETING_NOON = "中午好DJ，吃饱了才有力气搓碟哦"
    const val HOME_GREETING_AFTERNOON = "下午好DJ，来点轻松的House music吧"
    const val HOME_GREETING_EVENING = "夜幕降临，电音狂欢开始！晚上好DJ"
    const val HOME_TODAY_NOT_YET = "今日打碟台暂未营业 💿"
    const val HOME_KEEP_MOOD = "保持绝佳的Groove~ 🎵"
    const val HOME_DONT_FORGET_LOVE = "记得温柔对待自己哦 🌸"
    const val HOME_HEALTH_TIP_TITLE = "💡 驻场小贴士"
    const val HOME_HEALTH_MSG_TODAY_MANY = "碟片都要被你搓出火星子啦！让手指休息一下吧 DJ 🧯"
    const val HOME_HEALTH_MSG_TODAY_ONCE = "今日首单已发行，灵感爆棚，心情舒畅~ ✨"
    const val HOME_HEALTH_MSG_FREQUENT = "最近巡演排得太密啦，要注意保护手腕和身体哦 💙"
    const val HOME_HEALTH_MSG_HEALTHY = "发歌频率很完美！继续保持这个舒服的Beat~ 🎶"
    const val HOME_UNKNOWN_ERROR = "出现未知Bug，可能是音响炸了"
    const val HOME_DATE_PATTERN = "M月d日 EEEE"

    fun homeTodayRecorded(count: Int): String = "今日已搓 $count 次 ✨"

    // Statistics
    const val STAT_TAB_WEEK = "本周Live"
    const val STAT_TAB_MONTH = "本月歌单"
    const val STAT_TAB_ALL = "生涯总计"
    const val STAT_ADD_RECORD = "补录一场"
    const val STAT_EDIT_RECORD = "修改日志"
    const val STAT_DELETE_CONFIRM_TITLE = "真要删掉这场演出吗？"
    const val STAT_DELETE_CONFIRM_TEXT = "删了连母带都找不到咯。"
    const val STAT_WEEK_RECORD = "本周演出回放"
    const val STAT_CD_PREV_MONTH = "上个月"
    const val STAT_CD_NEXT_MONTH = "下个月"
    const val STAT_BACK_TO_CURRENT_MONTH = "回到本月"
    const val STAT_NO_RECORD = "暂无打碟记录，快去搞点创作"
    const val STAT_ADD_ONE_RECORD = "添加一条Live记录"
    const val STAT_LABEL_DATE = "演出日期"
    const val STAT_LABEL_TIME = "登台时间"
    const val STAT_LABEL_NOTE_OPTIONAL = "灵感备注（可选）"
    const val STAT_ERROR_DATE_TIME_INVALID = "时空乱流了，查查日期格式"
    const val STAT_TOTAL = "生涯总场次"
    const val STAT_MAX_STREAK = "最长连演"
    const val STAT_AVG_FREQUENCY = "平均发歌率"
    const val STAT_UNIT_TIMES = "场"
    const val STAT_UNIT_DAYS = "天"
    const val STAT_UNIT_TIMES_PER_WEEK = "场/周"
    const val STAT_ADVICE_LOW = "偶尔冒泡的独立音乐人，保持你的节奏就好！🎸"
    const val STAT_ADVICE_MEDIUM = "优秀的驻场DJ，状态绝佳，继续保持~ ✨"
    const val STAT_ADVICE_HIGH = "电音节劳模！虽然热情很高，但也别忘了给自己放个假哦 🛌"
    const val STAT_ADVICE_DEFAULT = "准备好记录你的第一首单曲了吗！"
    const val STAT_ADVICE_TITLE = "💡 厂牌建议"
    val STAT_WEEKDAY_HEADERS = listOf("一", "二", "三", "四", "五", "六", "日")

    fun statMonthTitle(year: Int, month: Int): String = "${year}年${month}月"
    fun statMonthTotal(total: Int): String = "共嗨 $total 场"
    fun statDayTitle(month: Int, day: Int): String = "${month}月${day}日"
    fun statDayCount(count: Int): String = "打碟 $count 次"

    // Settings (保持相对严谨，适当加emoji)
    const val SETTINGS_ENABLE_SYSTEM_AUTH_FIRST = "请先在系统设置中启用锁屏密码或生物识别"
    const val SETTINGS_EXPORT_SUCCESS = "母带导出成功 ✨"
    const val SETTINGS_EXPORT_FAILED = "导出失败了，磁带卡壳 😣"
    const val SETTINGS_RESTORE_SUCCESS = "数据恢复成功，爷青回 ✨"
    const val SETTINGS_RESTORE_INVALID = "数据格式不对哦，解析失败 😣"
    const val SETTINGS_RESTORE_FAILED = "恢复失败了 😣"
    const val SETTINGS_CLEAR_ALL_TITLE = "要烧毁所有唱片吗？"
    const val SETTINGS_CLEAR_ALL_TEXT = "不可逆操作哦！所有的搓碟记忆都会化为乌有。"
    const val SETTINGS_CLEARED = "唱片库已清空"
    const val SETTINGS_CLEAR_CONFIRM = "确认烧毁"
    const val SETTINGS_THINK_AGAIN = "我再想想"

    const val SETTINGS_WEBDAV_CONFIG_TITLE = "WebDAV 配置"
    const val SETTINGS_WEBDAV_SERVER_URL = "服务器地址"
    const val SETTINGS_WEBDAV_USERNAME = "用户名"
    const val SETTINGS_WEBDAV_PASSWORD = "密码"
    const val SETTINGS_WEBDAV_NEW_PASSWORD = "新密码（留空不改）"
    const val SETTINGS_WEBDAV_HINT = "备份文件会按当前导出格式上传，请妥善保管 WebDAV 账号。"
    const val SETTINGS_WEBDAV_DIRECTORY_OPTIONAL = "远程目录（可选）"
    const val SETTINGS_WEBDAV_CONFIG_SAVED = "WebDAV 配置已保存"
    const val SETTINGS_WEBDAV_CONFIG_SAVE_FAILED = "WebDAV 配置保存失败"

    const val SETTINGS_WEBDAV_RESTORE_TITLE = "从 WebDAV 恢复？"
    const val SETTINGS_WEBDAV_RESTORE_TEXT = "恢复会用云端最新备份替换本地记录，请确认已经选对备份来源。"
    const val SETTINGS_WEBDAV_RESTORE_CONFIRM = "确认恢复"
    const val SETTINGS_WEBDAV_RESTORE_SUCCESS = "WebDAV 恢复成功 ✨"
    const val SETTINGS_WEBDAV_RESTORE_FAILED = "WebDAV 恢复失败"

    const val SETTINGS_TITLE = "设置"
    const val SETTINGS_GROUP_PROFILE = "个人信息"
    const val SETTINGS_BIRTHDAY_PICK = "点击选择出生日期"
    const val SETTINGS_CURRENT_AGE = "当前年龄"
    const val SETTINGS_GROUP_SECURITY = "安全与隐私"
    const val SETTINGS_APP_LOCK = "应用锁"
    const val SETTINGS_APP_LOCK_SUBTITLE = "使用系统锁屏密码或生物识别"
    const val SETTINGS_GROUP_DATA = "数据管理"
    const val SETTINGS_BACKUP_DATA = "备份数据"
    const val SETTINGS_BACKUP_DATA_SUBTITLE = "用于数据迁移等场景"
    const val SETTINGS_RESTORE_DATA = "恢复数据"
    const val SETTINGS_RESTORE_DATA_SUBTITLE = "从 JSON 文件导入"
    const val SETTINGS_CLEAR_ALL = "清空所有数据"
    const val SETTINGS_CLEAR_ALL_SUBTITLE = "慎重操作"
    const val SETTINGS_GROUP_WEBDAV = "WebDAV 云备份"
    const val SETTINGS_WEBDAV_CONFIG = "WebDAV 配置"
    const val SETTINGS_WEBDAV_NOT_CONFIGURED = "未配置"
    const val SETTINGS_WEBDAV_TEST = "测试连接"
    const val SETTINGS_WEBDAV_TEST_SUBTITLE = "验证服务器地址和账号密码"
    const val SETTINGS_WEBDAV_TEST_OK = "WebDAV 连接正常"
    const val SETTINGS_WEBDAV_TEST_FAILED = "WebDAV 连接失败"
    const val SETTINGS_WEBDAV_BACKUP = "备份到 WebDAV"
    const val SETTINGS_WEBDAV_BACKUP_SUBTITLE = "上传为 quleme-backup-latest.json"
    const val SETTINGS_WEBDAV_BACKUP_OK = "WebDAV 备份成功 ✨"
    const val SETTINGS_WEBDAV_BACKUP_FAILED = "WebDAV 备份失败"
    const val SETTINGS_WEBDAV_RESTORE = "从 WebDAV 恢复"
    const val SETTINGS_WEBDAV_RESTORE_SUBTITLE = "下载云端最新备份并替换本地记录"

    fun settingsBirthDateText(date: String): String = "出生日期: $date"
    fun settingsAgeText(age: Int): String = "$age 岁"

    // Data layer errors
    const val WEBDAV_AUTH_FAILED = "WebDAV 认证失败"
    const val WEBDAV_NOT_FOUND = "未找到云端备份"

    fun webDavConnectionFailed(code: Int): String = "WebDAV 连接失败: $code"
    fun webDavUploadFailed(code: Int): String = "WebDAV 上传失败: $code"
    fun webDavDownloadFailed(code: Int): String = "WebDAV 下载失败: $code"
}
